### ISSUE TITLE
volume type quota with blockstorage_quotaset_v3 throws HTTP 400

### ISSUE THREAD

**Issue by birnemeier** [terraform-provider-openstack/terraform-provider-openstack#1207]
Hi,

when trying to use the new feature to set quota per volume type this error is thrown:

Error: Error updating openstack_blockstorage_quotaset_v3: Bad request with: [PUT https://xxxx:8776/v3/3090798ce37c41d984c1d0d1e9382cb5/os-quota-sets/4ec4f157060d444eb5f63cc16e3de144], error message: {"badRequest": {"code": 400, "message": "The server could not comply with the request since it is either malformed or otherwise incorrect."}}

This is what cinder logs, it sounds like the quota value for the volume_type is passed as a string. 

```
Exception handling resource:: TypeError: '<' not supported between instances of 'str' and 'int'
2021-03-15 13:03:26.501 40 ERROR cinder.api.openstack.wsgi Traceback (most recent call last):
2021-03-15 13:03:26.501 40 ERROR cinder.api.openstack.wsgi   File "/usr/lib/python3.6/site-packages/cinder/api/openstack/wsgi.py", line 899, in _process_stack
2021-03-15 13:03:26.501 40 ERROR cinder.api.openstack.wsgi     action_result = self.dispatch(meth, request, action_args)
2021-03-15 13:03:26.501 40 ERROR cinder.api.openstack.wsgi   File "/usr/lib/python3.6/site-packages/cinder/api/openstack/wsgi.py", line 994, in dispatch
2021-03-15 13:03:26.501 40 ERROR cinder.api.openstack.wsgi     return method(req=request, **action_args)
2021-03-15 13:03:26.501 40 ERROR cinder.api.openstack.wsgi   File "/usr/lib/python3.6/site-packages/cinder/api/validation/__init__.py", line 61, in wrapper
2021-03-15 13:03:26.501 40 ERROR cinder.api.openstack.wsgi     return func(*args, **kwargs)
2021-03-15 13:03:26.501 40 ERROR cinder.api.openstack.wsgi   File "/usr/lib/python3.6/site-packages/cinder/api/contrib/quotas.py", line 250, in update
2021-03-15 13:03:26.501 40 ERROR cinder.api.openstack.wsgi     quota_values)
2021-03-15 13:03:26.501 40 ERROR cinder.api.openstack.wsgi   File "/usr/lib/python3.6/site-packages/cinder/api/contrib/quotas.py", line 56, in _validate_existing_resource
2021-03-15 13:03:26.501 40 ERROR cinder.api.openstack.wsgi     if value < used:
2021-03-15 13:03:26.501 40 ERROR cinder.api.openstack.wsgi TypeError: '<' not supported between instances of 'str' and 'int'
2021-03-15 13:03:26.501 40 ERROR cinder.api.openstack.wsgi 
```

I was not able to log the body of the PUT-request with `OS_DEBUG=1 TF_LOG=DEBUG`. 

### Terraform Version

Terraform v0.14.7
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.39.0

Openstack is Victoria release

### Affected Resource(s)
- blockstorage_quotaset_v3

### Terraform Configuration Files
```hcl
resource "openstack_blockstorage_quotaset_v3" "quotaset_1" {
  per_volume_gigabytes           = 5000
  gigabytes                      = 7000
  volume_type_quota = {
    gigabytes_type-1            = 1000
  }
}
```

**Comment by nikParasyr** [comment]
Hello. This is duplicate of https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1193
This is being worked on.

**Comment by birnemeier** [comment]
Thanks for your work!
