### ISSUE TITLE
Updating openstack_networking_portfowarding_v2 resource crashes plugin

### ISSUE THREAD

**Issue by roflhouse** [terraform-provider-openstack/terraform-provider-openstack#1732]
Hey, I am seeing a crash in the openstack provider when attempting to update an openstack_networking_portforwarding_v2 resource. Basically, if you try to update to the port of a port forwarding resource from one port to another it causes a crash.

### Affected Resource(s)
openstack_networking_portfowarding_v2

### Terraform Configuration Files
I am using CDKTF but here is the generated resource plan output from terraform
```hcl
# openstack_networking_portforwarding_v2.redacted (redacted) will be updated in-place
       ~ resource "openstack_networking_portforwarding_v2" "redacted" {
             id                  = "..."
           ~ internal_ip_address = "172.29.X.X" -> "172.29.Y.Y"
           ~ internal_port_id    = "ID1" -> "ID2"
             # (5 unchanged attributes hidden)
         }
```

### Panic Output
```hcl
vpc  Stack trace from the terraform-provider-openstack_v1.54.1 plugin:
     panic: interface conversion: interface {} is nil, not string
     goroutine 27 [running]:
     github.com/terraform-provider-openstack/terraform-provider-openstack/openstack.resourceNetworkPortForwardingV2Update({0x1257c08, 0xc0005241b0}, 0xc000508400, {0x1094100?, 0xc00011afc0?})
     	github.com/terraform-provider-openstack/terraform-provider-openstack/openstack/resource_openstack_networking_portforwarding_v2.go:159 +0x865
     github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000459500, {0x1257c40, 0xc000506bd0}, 0xd?, {0x1094100, 0xc00011afc0})
     	github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:812 +0x12e
     github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000459500, {0x1257c40, 0xc000506bd0}, 0xc000439ba0, 0xc000508280, {0x1094100, 0xc00011afc0})
vpc  github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:919 +0x845
     github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000317fb0, {0x1257c40?, 0xc000506ab0?}, 0xc0001939f0)
     	github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/grpc_provider.go:1072 +0xe8d
     github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000450280, {0x1257c40?, 0xc0005060c0?}, 0xc000289b90)
     	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x574
     github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1078c20?, 0xc000450280}, {0x1257c40, 0xc0005060c0}, 0xc000289b20, 0x0)
     	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x170
     google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001401e0, {0x125bdf8, 0xc00047f6c0}, 0xc000504360, 0xc000465470, 0x191d958, 0x0)
     	google.golang.org/grpc@v1.57.1/server.go:1358 +0xe23
     google.golang.org/grpc.(*Server).handleStream(0xc0001401e0, {0x125bdf8, 0xc00047f6c0}, 0xc000504360, 0x0)
     	google.golang.org/grpc@v1.57.1/server.go:1735 +0xa36
     google.golang.org/grpc.(*Server).serveStreams.func1.1()
     	google.golang.org/grpc@v1.57.1/server.go:970 +0xca
     created by google.golang.org/grpc.(*Server).serveStreams.func1
     	google.golang.org/grpc@v1.57.1/server.go:981 +0x15c
     Error: The terraform-provider-openstack_v1.54.1 plugin crashed!
     This is always indicative of a bug within the plugin. It would be immensely
     helpful if you could report the crash with the plugin's maintainers so that it
     can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior
What should have happened?
The port forwarding resource should have been updated to use the new internal port address and port id or it should have deleted the resource and created a new resource with the correct data.

### Actual Behavior
What actually happened?
It crashed the plugin

### Steps to Reproduce
Create a port forwarding resource. then attempted to swap the resource to point to a different internal port.

### Important Factoids
I am running CDKTF.

**Comment by Koodt** [comment]
+1
